# 使用时需修改相关变量
version: '2'
networks:
  basic:
services:
  world:
    container_name: usersystem
    image: go-app
    ports:
      - "8099:80"
    volumes:
      - ./app/go/world:/go/src/app:rw
    networks:
      - basic
# version: '3.1'

# services:
#   api:
#     image: <your_docker_image>:<tag>
#     restart: always
#     ports:
#       - '3000:3000'
#     environment:
#       ENV: prod
#     volumes:
#       - '</example/public>:</app/public>