# mysql todo

DB_TYPE: 'mysql'
DB_USER: 'root'
DB_PASSWORD: '123456'
DB_HOST: '10.0.0.12:3306'
DB_NAME: 'clients'

#redis
RedisMaxIdle: 30
RedisMaxActive: 30
RedisIdleTimeout: 200
RedisHost: '10.0.0.12:6379'
RedisPassword: ''